version: '3'

services:
  web:
    container_name: handover
    image: vatsca/apache:php-8.1
    ports:
      - 5000:80
      - 5001:443
    networks:
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "vatsca.local:host-gateway"
    volumes:
      - /etc/vatsim/handover/html/:var/www/html
      - /etc/vatsim/handover/apache:/var/www/logs
    labels:
      # if you are not using traefik, comment out labels
      - "traefik.enable=true"
      - "traefik.http.routers.handover.entrypoints=http"
      - "traefik.http.routers.handover.rule=Host(`handover.local.dirtyformal.dev`)"
      - "traefik.http.middlewares.handover-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.handover.middlewares=portainer-https-redirect"
      - "traefik.http.routers.handover-secure.entrypoints=https"
      - "traefik.http.routers.handover-secure.rule=Host(`handover.local.dirtyformal.dev`)"
      - "traefik.http.routers.handover-secure.tls=true"
      - "traefik.http.routers.handover-secure.service=handover"
      - "traefik.http.services.handover.loadbalancer.server.port=5001"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
